import type { IProject } from "@/types";

export const projects: IProject[] = [
  {
    title: "MediPulse Portal",
    slug: "medipulse-portal",
    description: "Multi-tenant healthcare and pharmacy management platform implementing multi-tenant routing, 8-tier RBAC, JWT authentication, and a 7-stage order lifecycle.",
    longDescription: "Developed a multi-tenant healthcare and pharmacy management platform using Next.js, React, and TypeScript. Implemented multi-tenant routing, 8-tier RBAC, JWT authentication, and a 7-stage order lifecycle with dynamic questionnaires and real-time state synchronization.",
    techStack: ["Next.js 16", "React 19", "TypeScript", "MongoDB", "Mongoose", "Zustand", "TanStack Query", "TanStack Table", "Tailwind CSS", "SurveyJS", "Vitest"],
    features: [
      "Multi-tenant architecture isolating pharmacy and clinic workspaces",
      "Strict 8-tier Role-Based Access Control (RBAC) with JWT auth",
      "Dynamic clinical questionnaires powered by SurveyJS",
      "7-stage prescription order lifecycle with TanStack Table and TanStack Query",
      "Comprehensive automated test suite with 480+ unit and integration tests using Vitest",
    ],
    githubUrl: "https://github.com/harshit-1318",
    liveUrl: "",
    category: "FullStack",
    featured: true,
    image: "/medipulse_preview.png",
    metrics: {
      latency: "115ms (API)",
      efficiency: "480+ unit/integration tests",
      components: "8-tier RBAC & multi-tenant",
      testCoverage: "7-stage order lifecycle",
    },
    challenges: "Handling multi-tenant clinical routing, strict role-based access control across 8 user tiers, and managing complex patient order state.",
    solutions: "Designed multi-tenant routing architecture with Next.js 16 and Zustand. Integrated SurveyJS for dynamic medical questionnaires, TanStack Table for real-time order workflows, and maintained 480+ unit/integration tests using Vitest.",
    architectureSteps: [
      { title: "Multi-Tenant Routing", description: "Next.js App Router isolates pharmacy and healthcare clinic tenant namespaces." },
      { title: "8-Tier RBAC & Auth", description: "JWT-secured middleware validates permission tokens across 8 healthcare roles." },
      { title: "Clinical Surveys & Data Tables", description: "SurveyJS powers clinical intake forms while TanStack Table manages 7-stage order lifecycles." },
      { title: "Automated Testing Suite", description: "Maintained 480+ unit and integration tests using Vitest to guarantee clinical compliance." },
    ],
  },
  {
    title: "SolarShare",
    slug: "solarshare",
    description: "Peer-to-peer solar energy trading platform with role-based workflows, interactive dashboards, wallet/transactions, and real-time WebSocket updates.",
    longDescription: "Built a peer-to-peer solar energy trading platform with role-based workflows, interactive dashboards, wallet/transactions, JWT authentication, and real-time updates using Socket.IO.",
    techStack: ["MERN", "Vite", "Tailwind CSS", "Mongoose", "Socket.IO", "JWT"],
    features: [
      "Real-time P2P solar energy trading exchange powered by Socket.IO",
      "Role-based workflows and specialized dashboards for producers and consumers",
      "Digital energy credit wallet with secure ledger transactions",
      "JWT-secured session handling and MongoDB persistence",
    ],
    githubUrl: "https://github.com/harshit-1318",
    liveUrl: "",
    category: "FullStack",
    featured: true,
    image: "/solarshare_preview.png",
    metrics: {
      latency: "Sub-50ms Socket.IO",
      efficiency: "Real-time P2P energy trades",
      components: "Role-based dashboards & wallet",
      testCoverage: "JWT secured transactions",
    },
    challenges: "Delivering real-time bid-ask matching for renewable energy units without polling latency.",
    solutions: "Implemented bi-directional WebSockets via Socket.IO for live order books and integrated secure wallet transaction ledgers with Mongoose schemas.",
    architectureSteps: [
      { title: "Real-time WebSocket Feed", description: "Socket.IO synchronizes energy bid orders and price fluctuations in real time." },
      { title: "Role-Based Workflows", description: "Custom dashboards for energy producers, consumers, and grid operators." },
      { title: "Digital Energy Wallet", description: "JWT-secured transactions record energy credit transfers on MongoDB." },
      { title: "Vite Client Interface", description: "Fast responsive Tailwind CSS interface designed for desktop and mobile trade." },
    ],
  },
  {
    title: "EventElite",
    slug: "eventelite",
    description: "A full-stack event management platform with secure authentication, event creation, registration, and user management.",
    longDescription: "Developed a full-stack event management platform with secure authentication, event creation, registration, and user management features.",
    techStack: ["HTML", "CSS", "JavaScript", "Node.js", "Express.js", "MySQL"],
    features: [
      "Secure user authentication and role-based access control",
      "Event creation, editing, deletion, and attendee registration",
      "Interactive event calendars and user profile dashboards",
      "Relational database storage using MySQL with optimized search queries",
    ],
    githubUrl: "https://github.com/harshit-1318/eventelite",
    liveUrl: "",
    category: "FullStack",
    featured: true,
    image: "/eventelite_preview.png",
    metrics: {
      latency: "90ms",
      security: "JWT & Bcrypt Encryption",
      concurrency: "100+ registrations/min",
    },
    challenges: "Managing concurrent event registrations and preventing double-booking errors during high traffic periods.",
    solutions: "Implemented transaction isolation levels in MySQL queries and optimized database connection pooling.",
    architectureSteps: [
      { title: "Frontend Client", description: "Captured registration inputs and managed user session state." },
      { title: "API Route Validation", description: "Express middleware authenticated JWT tokens and sanitized inputs." },
      { title: "SQL Controller", description: "MySQL database stored relational registration and event tables." },
    ],
  },
  {
    title: "RentNest",
    slug: "rentnest",
    description: "An Airbnb-inspired rental booking platform featuring user authentication, property listings, booking workflows, and review management.",
    longDescription: "Built an Airbnb-inspired rental booking platform featuring user authentication, property listings, booking workflows, and review management.",
    techStack: ["Node.js", "Express.js", "MongoDB", "EJS"],
    features: [
      "Comprehensive property listing creation with image uploads",
      "Booking workflows with start/end date calculations",
      "Review management system for property feedback",
      "NoSQL storage with MongoDB schema validation",
    ],
    githubUrl: "https://github.com/harshit-1318/rentnest",
    liveUrl: "",
    category: "FullStack",
    featured: true,
    image: "/rentnest_preview.png",
    metrics: {
      latency: "110ms",
      dbLookup: "45ms index searches",
      coverage: "92% route tests",
    },
    challenges: "Developing a dynamic UI using EJS templates while handling complex nested documents for reviews and booking status states.",
    solutions: "Designed modular mongoose schemas with subdocuments and pre-save hooks to automatically aggregate review ratings.",
    architectureSteps: [
      { title: "EJS Layout rendering", description: "Renders server-side templates with dynamic data inputs." },
      { title: "Express routing", description: "Directs request threads to booking and property controller actions." },
      { title: "Mongoose database", description: "Stores collections for users, listings, bookings, and reviews." },
    ],
  },
];
