export const profileData = {
  name: "Harshit",
  title: "Frontend Developer",
  bio: "Frontend Developer with 1 year of professional experience building production-ready web applications using React.js, TypeScript, JavaScript, Astro, Vite, and Tailwind CSS. Experienced in reusable UI components, RESTful APIs, TanStack Query, data-driven dashboards, and frontend performance optimization.",
  email: "kumarharshit370@gmail.com",
  phone: "+91-7814283095",
  location: "Jalandhar, Punjab, India",
  logoColor1: "#6366f1",
  logoColor2: "#22d3ee",
  linkedinUrl: "https://www.linkedin.com/in/harshitkumar-dev1318",
  githubUrl: "https://github.com/harshit-1318",
  githubUsername: "harshit-1318",
  leetcodeUrl: "",
  leetcodeUsername: "",
  resumeUrl: "/resume/Resume_Harshit.pdf",
};
