export const skillsData = [
  { name: "HTML5", category: "Programming Languages", icon: "file-code", proficiency: 95, order: 1 },
  { name: "CSS3", category: "Programming Languages", icon: "palette", proficiency: 90, order: 2 },
  { name: "JavaScript (ES6+)", category: "Programming Languages", icon: "code-2", proficiency: 90, order: 3 },
  { name: "TypeScript", category: "Programming Languages", icon: "file-type", proficiency: 85, order: 4 },
  { name: "React.js", category: "Frontend", icon: "atom", proficiency: 90, order: 5 },
  { name: "Astro", category: "Frontend", icon: "layout", proficiency: 80, order: 6 },
  { name: "Vite", category: "Frontend", icon: "zap", proficiency: 85, order: 7 },
  { name: "Tailwind CSS", category: "Frontend", icon: "wind", proficiency: 95, order: 8 },
  { name: "Bootstrap", category: "Frontend", icon: "palette", proficiency: 80, order: 9 },
  { name: "React Hooks", category: "Frontend", icon: "hook", proficiency: 90, order: 10 },
  { name: "Context API", category: "Frontend", icon: "network", proficiency: 85, order: 11 },
  { name: "Zustand", category: "Frontend", icon: "box", proficiency: 80, order: 12 },
  { name: "REST APIs", category: "API & State", icon: "network", proficiency: 85, order: 13 },
  { name: "Axios", category: "API & State", icon: "send", proficiency: 90, order: 14 },
  { name: "TanStack Query", category: "API & State", icon: "search", proficiency: 85, order: 15 },
  { name: "TanStack Table", category: "API & State", icon: "table", proficiency: 85, order: 16 },
  { name: "Node.js", category: "Backend", icon: "server", proficiency: 75, order: 17 },
  { name: "Express.js", category: "Backend", icon: "route", proficiency: 80, order: 18 },
  { name: "NestJS", category: "Backend", icon: "cpu", proficiency: 60, order: 19 },
  { name: "MongoDB", category: "Database", icon: "database", proficiency: 75, order: 20 },
  { name: "MySQL", category: "Database", icon: "table", proficiency: 70, order: 21 },
  { name: "Git", category: "Tools", icon: "git-merge", proficiency: 85, order: 22 },
  { name: "GitHub", category: "Tools", icon: "github", proficiency: 85, order: 23 },
  { name: "Postman", category: "Tools", icon: "send", proficiency: 80, order: 24 },
  { name: "Vercel", category: "Tools", icon: "monitor", proficiency: 85, order: 25 },
  { name: "Shopify APIs", category: "Tools", icon: "shopping-bag", proficiency: 70, order: 26 }
];
